/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef ECHELONMENUS_API
#define ECHELONMENUS_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern ECHELONMENUS_API FName ECHELONMENUS_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif


#ifndef NAMES_ONLY


class ECHELONMENUS_API UEPCComboButton : public UUWindowComboButton
{
public:
    DECLARE_CLASS(UEPCComboButton,UUWindowComboButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCComboButton)
};


class ECHELONMENUS_API UEPCSBRightButton : public UUWindowSBRightButton
{
public:
    DECLARE_CLASS(UEPCSBRightButton,UUWindowSBRightButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCSBRightButton)
};


class ECHELONMENUS_API UEPCSBLeftButton : public UUWindowSBLeftButton
{
public:
    DECLARE_CLASS(UEPCSBLeftButton,UUWindowSBLeftButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCSBLeftButton)
};


class ECHELONMENUS_API UEPCSBUpButton : public UUWindowSBUpButton
{
public:
    DECLARE_CLASS(UEPCSBUpButton,UUWindowSBUpButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCSBUpButton)
};


class ECHELONMENUS_API UEPCSBDownButton : public UUWindowSBDownButton
{
public:
    DECLARE_CLASS(UEPCSBDownButton,UUWindowSBDownButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCSBDownButton)
};


class ECHELONMENUS_API UEPCTextButton : public UUWindowButton
{
public:
    DECLARE_CLASS(UEPCTextButton,UUWindowButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCTextButton)
};


class ECHELONMENUS_API UEPCInGameMenuMainButtons : public UUWindowButton
{
public:
    class UTexture* m_BackGroundTexture;
    DECLARE_CLASS(UEPCInGameMenuMainButtons,UUWindowButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameMenuMainButtons)
};


class ECHELONMENUS_API UEPCInGameInvButtons : public UUWindowButton
{
public:
    class UTexture* m_BackGroundTexture;
    BITFIELD m_bInvertHorizontalCoord:1 GCC_PACK(4);
    BITFIELD m_bHideWhenDisabled:1;
    INT m_CoordModifier GCC_PACK(4);
    DECLARE_CLASS(UEPCInGameInvButtons,UUWindowButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameInvButtons)
};


class ECHELONMENUS_API UEPCCheckBox : public UUWindowButton
{
public:
    DECLARE_CLASS(UEPCCheckBox,UUWindowButton,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCCheckBox)
};


class ECHELONMENUS_API UEPCComboList : public UUWindowComboList
{
public:
    DECLARE_CLASS(UEPCComboList,UUWindowComboList,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCComboList)
};


class ECHELONMENUS_API UEPCListBox : public UUWindowListBox
{
public:
    INT m_IRightPadding;
    DECLARE_FUNCTION(execRenderItem);
    DECLARE_CLASS(UEPCListBox,UUWindowListBox,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCListBox)
};


class ECHELONMENUS_API UEPCOptionKeysListBox : public UEPCListBox
{
public:
    INT TitleFont;
    INT m_IHighLightWidth;
    INT m_IHighLightRightPadding;
    class UTexture* m_BGTexture;
    BITFIELD m_bDoingAltMapping:1 GCC_PACK(4);
    TArrayNoInit<class UUWindowWindow*> m_Controls GCC_PACK(4);
    DECLARE_CLASS(UEPCOptionKeysListBox,UEPCListBox,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCOptionKeysListBox)
};


class ECHELONMENUS_API UEPCReconListBox : public UEPCListBox
{
public:
    DECLARE_CLASS(UEPCReconListBox,UEPCListBox,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCReconListBox)
};


class ECHELONMENUS_API UEPCLevelListBox : public UEPCListBox
{
public:
    DECLARE_CLASS(UEPCLevelListBox,UEPCListBox,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCLevelListBox)
};


class ECHELONMENUS_API UEPCFileListBox : public UEPCListBox
{
public:
    INT NameWidth;
    INT DateWidth;
    DECLARE_CLASS(UEPCFileListBox,UEPCListBox,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCFileListBox)
};


class ECHELONMENUS_API UEPCComboControl : public UUWindowComboControl
{
public:
    DECLARE_CLASS(UEPCComboControl,UUWindowComboControl,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCComboControl)
};


class ECHELONMENUS_API UEPCEditControl : public UUWindowEditControl
{
public:
    DECLARE_CLASS(UEPCEditControl,UUWindowEditControl,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCEditControl)
};


class ECHELONMENUS_API UEPCHScrollBar : public UUWindowHScrollbar
{
public:
    INT m_IScrollHeight;
    DECLARE_CLASS(UEPCHScrollBar,UUWindowHScrollbar,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCHScrollBar)
};


class ECHELONMENUS_API UEPCVScrollBar : public UUWindowVScrollbar
{
public:
    DECLARE_CLASS(UEPCVScrollBar,UUWindowVScrollbar,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCVScrollBar)
};


class ECHELONMENUS_API UEPCMainMenuRootWindow : public UUWindowRootWindow
{
public:
    class UEPCFileManager* m_FileManager;
    class UUWindowWindow* m_CurrentWidget;
    class UUWindowWindow* m_PreviousWidget;
    class UEPCMainMenu* m_MainMenuWidget;
    class UEPCVideoMenu* m_CreditsWidget;
    class UEPCVideoMenu* m_IntroWidget;
    class UEPCPlayerMenu* m_PlayerWidget;
    class UEPCOptionsMenu* m_OptionsWidget;
    class UEPCSaveGameMenu* m_SaveGameWidget;
    class UEPCInGameMenu* m_InGameMenu;
    class UEPCInGameDataDetailsMenu* m_InGameDataDetailsWidget;
    class UEPCIngameFakeWindow* m_FakeWidget;
    class UEPCPopUpController* m_MessageBoxCW;
    class UEPCMessageBox* m_MessageBox;
    class UTexture* ETPixel;
    class UMaterial* PdaBorder;
    class UTexture* PdaBackGround;
    BITFIELD bSkipLaptopOverlay:1 GCC_PACK(4);
    INT TitleFont GCC_PACK(4);
    BITFIELD ForceSmallFonts:1 GCC_PACK(4);
    DECLARE_CLASS(UEPCMainMenuRootWindow,UUWindowRootWindow,0|CLASS_Config,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCMainMenuRootWindow)
};


class ECHELONMENUS_API UEPCMenuPage : public UUWindowDialogClientWindow
{
public:
    DECLARE_CLASS(UEPCMenuPage,UUWindowDialogClientWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCMenuPage)
};


class ECHELONMENUS_API UEPCVideoMenu : public UEPCMenuPage
{
public:
    class UCanvas* PlayCanvas;
    BITFIELD m_bFirstTime:1 GCC_PACK(4);
    FStringNoInit m_VideoName GCC_PACK(4);
    DECLARE_CLASS(UEPCVideoMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCVideoMenu)
};


class ECHELONMENUS_API UEPCSaveGameMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_Back;
    INT m_IBackButtonsXPos;
    INT m_IBackButtonsHeight;
    INT m_IBackButtonsWidth;
    INT m_IBackButtonsYPos;
    class UEPCTextButton* m_SaveGamesButton;
    class UEPCTextButton* m_LevelsButton;
    INT m_iTopButtonsYPos;
    INT m_iFSaveGamesXPos;
    INT m_iLevelsXPos;
    INT m_iTopButtonsWidth;
    class UEPCTextButton* m_ConfirmationButton;
    INT m_iConfirmationXPos;
    class UEPCLevelListBox* m_ListBox;
    class UEPCFileListBox* m_FileListBox;
    INT m_IListBoxXPos;
    INT m_IListBoxYPos;
    INT m_IListBoxWidth;
    INT m_IListBoxHeight;
    INT m_ISaveListBoxYPos;
    INT m_ISaveListBoxHeight;
    class UUWindowLabelControl* m_LName;
    class UUWindowLabelControl* m_LDate;
    class UUWindowLabelControl* m_LTime;
    FColor m_TextColor;
    INT m_ILabelHeight;
    INT m_NameWidth;
    INT m_LDateWidth;
    DECLARE_CLASS(UEPCSaveGameMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCSaveGameMenu)
};


class ECHELONMENUS_API UEPCPlayerMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_MainMenu;
    INT m_IMainButtonsXPos;
    INT m_IMainButtonsHeight;
    INT m_IMainButtonsWidth;
    INT m_IMainButtonsYPos;
    class UEPCTextButton* m_LoadButton;
    class UEPCTextButton* m_CreateButton;
    INT m_iTopButtonsYPos;
    INT m_iLoadXPos;
    INT m_iCreateButtonXPos;
    INT m_iTopButtonsWidth;
    class UEPCTextButton* m_ConfirmationButton;
    INT m_iConfirmationXPos;
    class UEPCCreatePlayerArea* m_CreateArea;
    class UEPCLoadDelPlayerArea* m_LoadDelArea;
    INT m_iCreateXPos;
    INT m_iCreateYPos;
    INT m_iCreateWidth;
    INT m_iCreateHeight;
    DECLARE_CLASS(UEPCPlayerMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCPlayerMenu)
};


class ECHELONMENUS_API UEPCOptionsMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_MainMenu;
    class UEPCTextButton* m_ResetToDefault;
    INT m_IMainButtonsXPos;
    INT m_IMainButtonsHeight;
    INT m_IMainButtonsWidth;
    INT m_IMainButtonsYPos;
    INT m_IResetToDefaultXPos;
    class UEPCTextButton* m_Controls;
    class UEPCTextButton* m_Graphics;
    class UEPCTextButton* m_Sounds;
    INT m_iSectionButtonsYPos;
    INT m_iFirstSectionButtonsXPos;
    INT m_iSectionButtonsXOffset;
    INT m_iSectionButtonsWidth;
    class UEPCVideoConfigArea* m_GraphicArea;
    class UEPCSoundConfigArea* m_SoundsArea;
    class UEPCControlsConfigArea* m_ControlsArea;
    INT m_IAreaXPos;
    INT m_IAreaYPos;
    INT m_IAreaWidth;
    INT m_IAreaHeight;
    class UEPCMessageBox* m_MessageBox;
    DECLARE_CLASS(UEPCOptionsMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCOptionsMenu)
};


class ECHELONMENUS_API UEPCInGameSettingsArea : public UEPCOptionsMenu
{
public:
    DECLARE_CLASS(UEPCInGameSettingsArea,UEPCOptionsMenu,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameSettingsArea)
};


class ECHELONMENUS_API UEPCMessageBox : public UEPCMenuPage
{
public:
    class UUWindowLabelControl* m_TitleLabel;
    class UEPCTextButton* m_YesButton;
    class UEPCTextButton* m_NoButton;
    class UEPCTextButton* m_OKButton;
    class UEPCTextButton* m_CancelButton;
    class UUWindowWrappedTextArea* m_MessageArea;
    FRegion Left;
    FRegion Mid;
    FRegion Right;
    BYTE EnterResult;
    class UFont* m_TextAreaFont;
    FColor m_TextAreaColor;
    DECLARE_CLASS(UEPCMessageBox,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCMessageBox)
};


class ECHELONMENUS_API UEPCMainMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_StarGame;
    class UEPCTextButton* m_Settings;
    class UEPCTextButton* m_PlayIntro;
    class UEPCTextButton* m_Credits;
    class UEPCTextButton* m_ExitGame;
    class UEPCTextButton* m_GoOnline;
    INT m_IMainButtonsXPos;
    INT m_IMainButtonsHeight;
    INT m_IMainButtonsWidth;
    INT m_IMainButtonsFirstYPos;
    INT m_IMainButtonsYOffset;
    INT m_IGoOnlineYPos;
    INT m_IGoOnlineWidth;
    INT m_IGoOnlineXPos;
    class UEPCMessageBox* m_MessageBox;
    DECLARE_CLASS(UEPCMainMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCMainMenu)
};


class ECHELONMENUS_API UEPCInGameSaveGameArea : public UEPCMenuPage
{
public:
    class UUWindowLabelControl* m_TitleLabel;
    INT m_ITitleYPos;
    INT m_ITitleXPos;
    class UEPCTextButton* m_OKButton;
    class UEPCTextButton* m_CancelButton;
    INT m_IButtonWidth;
    INT m_IButtonsYPos;
    INT m_IOKXPos;
    INT m_ICancelXPos;
    class UEPCEditControl* m_SaveGameName;
    INT m_ISaveGameWidth;
    INT m_ISaveGameYpos;
    INT m_ITextHeight;
    FColor m_EditBorderColor;
    INT m_IBGXPos;
    INT m_IBGYPos;
    INT m_IBGWidth;
    INT m_IBGHeight;
    class UTexture* m_BGTexture;
    DECLARE_CLASS(UEPCInGameSaveGameArea,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameSaveGameArea)
};


class ECHELONMENUS_API UEPCInGameMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_MainMenu;
    class UEPCTextButton* m_GoToGame;
    INT m_IMainButtonsXPos;
    INT m_IMainButtonsHeight;
    INT m_IMainButtonsWidth;
    INT m_IMainButtonsYPos;
    INT m_IGoToGameButtonXPos;
    class UEPCInGameMenuMainButtons* m_BInventory;
    class UEPCInGameMenuMainButtons* m_BSaveLoad;
    class UEPCInGameMenuMainButtons* m_BSettings;
    class UEPCInGameMenuMainButtons* m_BMissionInfo;
    INT m_IYFirstButtonPos;
    INT m_IYButtonOffset;
    INT m_IButtonHeight;
    INT m_IXButtonPos;
    INT m_IButtonWidth;
    class UEPCInGameMissionInfoArea* m_MissionInfoArea;
    class UEPCInGameInventoryArea* m_InventoryArea;
    class UEPCInGameSettingsArea* m_SettingsArea;
    class UEPCInGameSaveLoadArea* m_SaveLoadArea;
    class UEPCInGameSectionInfoArea* m_SectionInfoArea;
    class UUWindowWindow* m_SelectedArea;
    INT m_IAreaXPos;
    INT m_IAreaYPos;
    INT m_IAreaWidth;
    INT m_IAreaHeight;
    class UEPCMessageBox* m_MessageBoxMain;
    class UEPCMessageBox* m_MessageBoxSettings;
    BITFIELD m_bStartGame:1 GCC_PACK(4);
    BITFIELD m_bAskExitToMenu:1;
    DECLARE_CLASS(UEPCInGameMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameMenu)
};


class ECHELONMENUS_API UEPCInGameDataDetailsMenu : public UEPCMenuPage
{
public:
    class UEPCTextButton* m_Return;
    INT m_IReturnButtonsXPos;
    INT m_IReturnButtonsHeight;
    INT m_IReturnButtonsWidth;
    INT m_IReturnButtonsYPos;
    class UERecon* m_Recon;
    class UEPCVScrollBar* m_ScrollBar;
    BITFIELD m_BInitScrollBar:1 GCC_PACK(4);
    INT m_INbScroll GCC_PACK(4);
    INT m_INbLinesDisplayed;
    DECLARE_CLASS(UEPCInGameDataDetailsMenu,UEPCMenuPage,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameDataDetailsMenu)
};


class ECHELONMENUS_API UEPCInGameSaveLoadArea : public UUWindowDialogClientWindow
{
public:
    class UEPCTextButton* m_LoadGameButton;
    class UEPCTextButton* m_LoadLevelButton;
    class UEPCTextButton* m_SaveGameButton;
    class UEPCTextButton* m_LoadConfirmationButton;
    INT m_IFirstButtonsXPos;
    INT m_IXButtonOffset;
    INT m_IButtonsHeight;
    INT m_IButtonsWidth;
    INT m_IButtonsYPos;
    INT m_iLoadXPos;
    INT m_ILoadYPos;
    INT m_ILoadWidth;
    INT m_ILoadHeight;
    class UEPCLevelListBox* m_ListBox;
    class UEPCFileListBox* m_FileListBox;
    INT m_IListBoxXPos;
    INT m_IListBoxYPos;
    INT m_IListBoxWidth;
    INT m_IListBoxHeight;
    INT m_ISaveListBoxYPos;
    INT m_ISaveListBoxHeight;
    class UEPCInGameSaveGameArea* m_SaveArea;
    class UUWindowLabelControl* m_LName;
    class UUWindowLabelControl* m_LDate;
    class UUWindowLabelControl* m_LTime;
    FColor m_TextColor;
    INT m_ILabelHeight;
    INT m_NameWidth;
    INT m_LDateWidth;
    class UEPCMessageBox* m_MessageBox;
    class UEPCMessageBox* m_SavingLoadingMessageBox;
    BITFIELD m_bSkipOne:1 GCC_PACK(4);
    DECLARE_CLASS(UEPCInGameSaveLoadArea,UUWindowDialogClientWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameSaveLoadArea)
};


class ECHELONMENUS_API UEPCInGameInventoryArea : public UUWindowDialogClientWindow
{
public:
    class UEPCTextButton* m_sc20kButton;
    class UEPCTextButton* m_GadgetsButton;
    class UEPCTextButton* m_ItemsButton;
    class UEPCTextButton* m_SelectedButton;
    INT m_IFirstButtonsXPos;
    INT m_IXButtonOffset;
    INT m_IButtonsHeight;
    INT m_IButtonsWidth;
    INT m_IButtonsYPos;
    BYTE m_CurrentCategory;
    class UEPCInGameInvButtons* m_ArrowLeftButton;
    class UEPCInGameInvButtons* m_ArrowRightButton;
    class UEPCInGameInvButtons* m_InventoryButtons[4];
    INT m_IArrowLeftXPos;
    INT m_IArrowRightXPos;
    INT m_IArrowButtonWidth;
    INT m_IInvButtonWidth;
    INT m_IInvButtonHeight;
    INT m_IFirstInvButtonXPos;
    INT m_IInvButtonXOffset;
    INT m_IInvYPos;
    INT m_ISelectedItem;
    BITFIELD m_bGadgetVideoIsPlaying:1 GCC_PACK(4);
    INT m_IXVideoPos GCC_PACK(4);
    INT m_IYVideoPos;
    INT m_IVideoWidth;
    INT m_IXVideoHeight;
    class UEPCVScrollBar* m_ScrollBar;
    BITFIELD m_BInitScrollBar:1 GCC_PACK(4);
    INT m_INbScroll GCC_PACK(4);
    INT m_INbLinesDisplayed;
    DECLARE_CLASS(UEPCInGameInventoryArea,UUWindowDialogClientWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameInventoryArea)
};


class ECHELONMENUS_API UEPCInGameGoalsArea : public UUWindowDialogClientWindow
{
public:
    class UEPCVScrollBar* m_ScrollBar;
    BITFIELD m_bGoals:1 GCC_PACK(4);
    INT m_IGoalCurScroll GCC_PACK(4);
    INT m_IGoalNbScroll;
    INT m_INoteCurScroll;
    INT m_INoteNbScroll;
    BITFIELD m_bCompute:1 GCC_PACK(4);
    DECLARE_CLASS(UEPCInGameGoalsArea,UUWindowDialogClientWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameGoalsArea)
};


class ECHELONMENUS_API UEPCInGameDataArea : public UUWindowDialogClientWindow
{
public:
    class UEPCReconListBox* m_ListBox;
    INT m_IListBoxXPos;
    INT m_IListBoxYPos;
    INT m_IListBoxWidth;
    INT m_IListBoxHeight;
    DECLARE_CLASS(UEPCInGameDataArea,UUWindowDialogClientWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameDataArea)
};


class ECHELONMENUS_API UEPCInGameSectionInfoArea : public UUWindowWindow
{
public:
    class UUWindowLabelControl* m_LHelpText;
    INT m_IXLabelPos;
    INT m_IYLabelPos;
    INT m_ILabelWidth;
    INT m_ILabelHeight;
    FColor m_TextColor;
    DECLARE_CLASS(UEPCInGameSectionInfoArea,UUWindowWindow,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCInGameSectionInfoArea)
};


class ECHELONMENUS_API UEPCOptionsKeyListBoxItem : public UUWindowListBoxItem
{
public:
    BITFIELD m_bisTitle:1 GCC_PACK(4);
    BITFIELD m_bIsNotSelectable:1;
    FStringNoInit m_szActionKey GCC_PACK(4);
    class UUWindowWindow* m_Control;
    FStringNoInit HelpText2;
    BITFIELD m_bDrawFlipped:1 GCC_PACK(4);
    BITFIELD bIsCheckBoxLine:1;
    DECLARE_CLASS(UEPCOptionsKeyListBoxItem,UUWindowListBoxItem,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCOptionsKeyListBoxItem)
};


class ECHELONMENUS_API UEPCListBoxItem : public UUWindowListBoxItem
{
public:
    FStringNoInit m_AltText;
    FStringNoInit szSortByToken;
    class UObject* m_Object;
    BITFIELD m_bLocked:1 GCC_PACK(4);
    BITFIELD m_bReverseSort:1;
    DECLARE_CLASS(UEPCListBoxItem,UUWindowListBoxItem,0,EchelonMenus)
    NO_DEFAULT_CONSTRUCTOR(UEPCListBoxItem)
};

#endif

AUTOGENERATE_FUNCTION(UEPCListBox,4008,execRenderItem);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
