/*===========================================================================
    C++ class definitions exported from UnrealScript.
    This is automatically generated by the tools.
    DO NOT modify this manually! Edit the corresponding .uc files instead!
===========================================================================*/
#if SUPPORTS_PRAGMA_PACK
#pragma pack (push,4)
#endif

#ifndef EDITOR_API
#define EDITOR_API DLL_IMPORT
#endif

#ifndef NAMES_ONLY
#define AUTOGENERATE_NAME(name) extern EDITOR_API FName EDITOR_##name;
#define AUTOGENERATE_FUNCTION(cls,idx,name)
#endif

AUTOGENERATE_NAME(Build)
AUTOGENERATE_NAME(CreateMaterial)

#ifndef NAMES_ONLY

#define UCONST_RF_Standalone 0x00080000
#define UCONST_RF_Public 0x0000004

struct UMaterialFactory_eventCreateMaterial_Parms
{
    class UObject* InOuter;
    FString InPackage;
    FString InGroup;
    FString InName;
    class UMaterial* ReturnValue;
};
class EDITOR_API UMaterialFactory : public UObject
{
public:
    FStringNoInit Description;
    DECLARE_FUNCTION(execConsoleCommand);
    class UMaterial* eventCreateMaterial(class UObject* InOuter, const FString& InPackage, const FString& InGroup, const FString& InName)
    {
        UMaterialFactory_eventCreateMaterial_Parms Parms;
        Parms.ReturnValue=0;
        Parms.InOuter=InOuter;
        Parms.InPackage=InPackage;
        Parms.InGroup=InGroup;
        Parms.InName=InName;
        ProcessEvent(FindFunctionChecked(EDITOR_CreateMaterial),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UMaterialFactory,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UMaterialFactory)
};


struct UBrushBuilder_eventBuild_Parms
{
    BITFIELD ReturnValue;
};
class EDITOR_API UBrushBuilder : public UObject
{
public:
    FStringNoInit BitmapFilename;
    FStringNoInit ToolTip;
    TArrayNoInit<FVector> Vertices;
    TArrayNoInit<FBuilderPoly> Polys;
    FName Group;
    BITFIELD MergeCoplanars:1 GCC_PACK(4);
    DECLARE_FUNCTION(execPolyEnd);
    DECLARE_FUNCTION(execPolyi);
    DECLARE_FUNCTION(execPolyBegin);
    DECLARE_FUNCTION(execPoly4i);
    DECLARE_FUNCTION(execPoly3i);
    DECLARE_FUNCTION(execVertex3f);
    DECLARE_FUNCTION(execVertexv);
    DECLARE_FUNCTION(execBadParameters);
    DECLARE_FUNCTION(execGetPolyCount);
    DECLARE_FUNCTION(execGetVertex);
    DECLARE_FUNCTION(execGetVertexCount);
    DECLARE_FUNCTION(execEndBrush);
    DECLARE_FUNCTION(execBeginBrush);
    BITFIELD eventBuild()
    {
        UBrushBuilder_eventBuild_Parms Parms;
        Parms.ReturnValue=0;
        ProcessEvent(FindFunctionChecked(EDITOR_Build),&Parms);
        return Parms.ReturnValue;
    }
    DECLARE_CLASS(UBrushBuilder,UObject,0,Editor)
    NO_DEFAULT_CONSTRUCTOR(UBrushBuilder)
};

#endif

AUTOGENERATE_FUNCTION(UMaterialFactory,-1,execConsoleCommand);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyEnd);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyi);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPolyBegin);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly4i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execPoly3i);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertex3f);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execVertexv);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBadParameters);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetPolyCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertex);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execGetVertexCount);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execEndBrush);
AUTOGENERATE_FUNCTION(UBrushBuilder,-1,execBeginBrush);

#ifndef NAMES_ONLY
#undef AUTOGENERATE_NAME
#undef AUTOGENERATE_FUNCTION
#endif

#if SUPPORTS_PRAGMA_PACK
#pragma pack (pop)
#endif
